self-xdsd/self-core

.gitignore
pom.xml
self-api/pom.xml
self-core-impl/pom.xml

#1 Maven structure

---

self-api/src/main/java/Repo.java
self-api/src/main/java/Repos.java
self-api/src/main/java/Self.java
self-api/src/main/java/User.java

#3 first interfaces

---

pom.xml
self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Repo.java

Fixes #3 
Left a ``todo`` to continue work in a future task.

Introduced the Project Interface

---

self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/Self.java
self-api/src/main/java/com/selfxdsd/api/User.java

Fixes #10 
Introduced ``Projects`` and let 2 puzzles, 1 for continuing with the interfaces and 1 to start with the core implementation.

#10 Projects and User.projects()

---

self-api/src/main/java/com/selfxdsd/api/Storage.java
self-api/src/main/java/com/selfxdsd/api/Users.java
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubSelfTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryUsers.java

Fixes #13 
Implemented GithubSelf with User sign-up (authentication) and unit test for it.
Added the ``InMemory`` mock Storage used in unit tests and left puzzle for testing it.

#13 GithubSelf login + InMemory storage + unit test

---

.travis.yml
pom.xml

testCoverage profile for maven

---

self-api/pom.xml
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java

Resolves #15 
Implemented and tested GithubRepo.
Left puzzles for continuing with Github Repos imlementation, as well as GithubRepo.activate().

Implemented GithubRepo

---

.rultor.yml
.travis.yml
pom.xml

#19 use java 11

---

.rultor.yml
.travis.yml
README.md
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java

PR for #26 
* Implemented Github.repo(...)
* Implemented BaseRepo.json()
* added todo for using a mock server for unit tests
* wrote integration tests for BaseRepo.json()

Implemented Github.repo

---

pom.xml
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/Storage.java
self-api/src/main/java/com/selfxdsd/api/StoredProjectManager.java
self-api/src/test/java/com/selfxdsd/api/StoredProjectManagerTestCase.java
self-core-impl/pom.xml
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java

PR for #29 
* Implemented StoredProjectManager
* wrote unit tests for it
* added in-memory Storage methods
* left todos to continue implementation.

Implemented and tested StoredProjectManager

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java

Fixes #33 
Decided to cache the result of this.json(), instead of fetching the value in the constructor.

#33 cache the repo json

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

PR for #21 
Wrote only a shallow unit test which should be revised once possible.

#21 BaseRepo.activate() implemented and tested

---

checkstyle.xml
self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/StoredProjectManager.java
self-api/src/test/java/com/selfxdsd/api/StoredProjectManagerTestCase.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java

PR for #32 
* Project interface
* Projects.register(...)
* Implemented the ``in memory`` Projects storage for tests.

Projects Storage

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTestCase.java

PR for #16 
Testing InMemoryUsers.

added Users test cases for InMemory storage.

---

self-api/src/main/java/com/selfxdsd/api/StoredProject.java
self-api/src/test/java/com/selfxdsd/api/StoredProjectManagerTestCase.java
self-api/src/test/java/com/selfxdsd/api/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

PR for #31 
Implemented the PM assignment method
Unit and integration tests.

Implemented StoredProjectManager.assign(...)

---

self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProject.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProjectManager.java
self-api/src/test/java/com/selfxdsd/api/storage/StoredProjectManagerTestCase.java
self-api/src/test/java/com/selfxdsd/api/storage/StoredProjectTestCase.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubSelfTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTestCase.java

#41 storage package for the API

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProject.java

PR for #12 
Introduced the Contributor and the Contract association between a Contributor and a Project.

#12 Project-Contracts-Contributor api

---

self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabTestCase.java

PR for #36 
Integration tests for Gitlab over network. 
Tested finding a repo and its json format.

Implemented Gitlab and GitlabRepo.

---

self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProject.java

#45 Contracts.ofProject(int) and Contracts.Empty

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProject.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProjectManager.java
self-api/src/test/java/com/selfxdsd/api/storage/StoredProjectManagerTestCase.java
self-api/src/test/java/com/selfxdsd/api/storage/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java

#50 Implemented int :: Project.projectId()

---

self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProject.java
self-api/src/test/java/com/selfxdsd/api/storage/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

PR for #45 
Implemented the contracts method
tested it
Left puzzle to continue with the InMemory implementation.

StoredProject.contracts() + puzzle

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java

PmProjects implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/SelfCore.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

Solves #59 
* Implemented UserProjects
* Implemented Projects.ownedBy(User)
* Implemented User.projects()
* Wrote unit tests.

Implemented User.projects()

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/storage/StoredProjectManager.java
self-api/src/test/java/com/selfxdsd/api/storage/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java

#66 ProjectManager.provider() implemented and tested

---

pom.xml
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

#69 move classes into core

---

self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

#74 Contracts.ofContributor implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

PR for #73 
* Implemented and tested ``ProjectContracts``
* Implemented and tested ``ContributorContracts``
* Used the 2 classes inside ``InMemoryContracts``

ProjectContracts and ContributorContracts

---

self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java

PR for #77 
Implemented and tested ``Contracts.addContract``
Left puzzle to update InMemoryContracts and its tests when Storage has contributors added to its API.

Implemented and tested addContract for InMemoryContracts.java

---

self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-api/src/main/java/com/selfxdsd/api/Repo.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java

Pull request for #68.
Implemented the provider to be taken into account when choosing a PM for a Repo.
Left puzzle in InMemoryProjectManagers class for adding ProjectManager from each repository and to update the unit test.

#68 - Pick project manager from the repository provider.

---

self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java

PR for #83 
Added Gitlab pm in InMemoryProjectManagers
Updated InMemoryProjectManagers#pick searching
Fixed tests that are using InMemoryProjectManagers Gitlab pm id
Updated ProjectManagers#pick javadoc
Added puzzle to create a 'addProjectManager' in ProjectManagers

Updated InMemoryProjectManagers with Gitlab provider

---

checkstyle.xml
pom.xml
self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java

fixes #84 
* The Contributor's PK is his username + provider
* ``Contracts.ofContributor(int)`` -> ``Contracts.ofContributor(Contributor)``
* Implemented ``StoredContributor`` and fixed existing tests
* Added unit tests for ``StoredContributor``

Contributor Key = username + provider

---

self-core-impl/pom.xml

#48 self-api scope provided

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java

#82 Continue creating Unit Tests

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Issues.java
self-api/src/main/java/com/selfxdsd/api/Repo.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssues.java

Fixes #97 
* Added interfaces Issues and Issue
* Added classes GithubIssues and GithubIssue
* Left puzzles

Started implementing Issues

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

#94 Implemented StoredContract and StoredContractTestCase

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java

#95 - Implement InMemoryContributorsTestCase

---

self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/issues/GithubIssuesITCase.java

PR for #101
Added an internal utility class to fetch json objects remotely.
Added a temporary cache for fetched issues until Storage has that feature.
Created puzzle to extract the json utility class into its own file and then refactor BaseRepo#json to use it.

Implemented and tested method json() in GithubIssues

---

self-api/src/main/java/com/selfxdsd/api/Projects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java

Pull request for #96 .
Implemented getByProjectId method and unit test.
Left puzzle in InMemoryProjectsTestCase to continue tests for other types of projects.

#96 - Implement Projects getByProjectId method.

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java

fixes #107 
* role is part of the Contract PK
* unit tests
* added constants for the possible roles

Role is part of the Contract PK

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java

Fixes #110 
* Iplemented the method
* made InMemoryContracts throw ISE if Contract already exists
* added unit tests
* Made ContributorContracts take Storage in constructor
* Left puzzle to implement ``ContributorContracts.addContract``

Implemented ProjectContracts.addContract

---

self-api/src/main/java/com/selfxdsd/api/Projects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

#108 Provided and tested implementations of Projects#getProjectById().

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java

#112 implemented and tested ContributorContracts.addContract

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

PR for #117 
Added method ofProject(id) in Contributors
Stubbed ofProject(id) in InMemoryContributors
Implemented and tested contributors in StoredProject
Added puzzle to create class ProjectContributors in contributors package.

#117 Implemented Contributors::project.contributors().

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

PR for #116 
* Interface Tasks
* interface Task
* implemented StoredTask
* unit tests for StoredTask
* puzzle to continue with Tasks.

Tasks, Task and StoredTask

---

self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java

PR for #123 
Left puzzle for registering a new Task.

#123 InMemoryTasks + Task::getById

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/issues/GithubIssueTestCase.java

Fixes #126 
Also wrote unit tests and removed the corresponding puzzle.

Implemented Issue.issueId and Issue.role

---

self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/Repo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

fixes #129 
Changed the projectId from incremented integer to repoFullName + provider.

ProjectId = repoFullName + provider

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/issues/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java

Fixes #125 
* Implemented Tasks.register based on the Issue
* Wrote unit tests for InMemoryTasks
* Left puzzle to continue work on Tasks

Tasks.register implemented

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

PR for #133 
* Project.tasks()
* Implemented and tested StoredProject.tasks()
* Implemented and tested ProjectTasks
* left puzzles to continue work.

#133 Project.tasks(), ProjectTasks + unit tests

---

self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

#134 repoFullName part of Task PK

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java

PR for #137 
Implemented and unit tested method `ofProject` in InMemoryTasks.
Removed puzzle.

#137 Implemented and unit tested method `ofProject` in InMemoryTasks.

---

self-api/src/main/java/com/selfxdsd/api/Provider.java
self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubLogin.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabLogin.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubLoginTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabLoginTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java

Fixes #142 
* removed User.avatar(). No need to store the avatar URL in the DB.
* implemented and tested StoredUser
* Used it instead of anonymous classes

StoredUser implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java

#146 - Added `accessToken` to Github and Gitlab provider implementation.

---

.gitignore
.rultor.yml
README.md
release.sh

PR for #147 
Added release configs

Release Config

---

.rultor.yml
pom.xml
release.sh

#150 genDocs profile for javadocs and sources

---

self-api/src/main/java/com/selfxdsd/api/Login.java
self-api/src/main/java/com/selfxdsd/api/Users.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubLogin.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabLogin.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryUsers.java

#155 Users.signUp(...) refactored

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#152 StoredProject constructor redesigned

---

self-api/src/main/java/com/selfxdsd/api/Provider.java
self-api/src/main/java/com/selfxdsd/api/Users.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryUsers.java

PR for #153, based on [this](https://github.com/self-xdsd/self-core/issues/153#issuecomment-636643821) comment.
* Implemented Authenticated decorator for a user who has an accessToken;
* Implemented Provider.withToken(...) to return a new version of it which contains the token.

Implemented Authenticated user

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/InvoiceTask.java
self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

PR for #161 
Added puzzle to implement and test InMemoryInvoices; also test the Invoice/Invoices API.

#161 Invoice/Invoices API for Contract.

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

fixes #165 
Left puzzle to finish implementation of ``StoredTask.issue()``.

#165 StoredTask lazy-loads the Issue.

---

self-api/src/main/java/com/selfxdsd/api/Issues.java
self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/issues/GithubIssuesITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

PR for #167 
* Issues.getById expects String;
* Implemented StoredTask.issue();
* Wrote unit test;

Implemented StoredTask.issue()

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java

PR for #121 
* Implemented and tested ProjectContributors
* Implemented and tested InMemoryContributors.ofProject

ProjectContributors implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/InvoiceTask.java
self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicesTestCase.java

PR for #164 
Left puzzle to continue testing it and do some refactoring.

#164 Implemented and partially tested InMemoryInvoices.

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java

Added PM username

---

self-api/src/main/java/com/selfxdsd/api/Self.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

#180 Self.projectManagers() + unit test

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicesTestCase.java

PR for #175 
Left puzzle to refactor and test ContractInvoices.

#175 - Finished testing InMemoryInvoices.

---

README.md

Just a fix typo

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

Fixes #162 
* Implemented and tested Project.webHookToken()
* Modified Projects.register to also accept the token.

#162 Added Project.webHookToken()

---

self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

PR for #187 
Implemented and tested UnassignedTasks.
Left puzzle to implement and test unassigned() for ProjectTasks and InMemoryTasks.

#187 - Added unassigned() method in Tasks.

---

self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

#194 Storage extends AutoCloseable

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java

PR for #192 
* Started implementing Contributors.elect
* Regarding #197 -- we now have the option to load the Contributor's Contracts eagerly (StoredContributor accepts the Contracts as ctor parameter)

#192 Contributors.elect scaffolding

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

PR for #201
Left puzzle to continue implementing and testing ContractTasks.

#201 Started implementing and testing Contract#tasks.

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java

PR for #203 
Left puzzle to implement and test ofContract() in ProjectTasks, ContributorTasks and InMemoryTasks using ContractTasks.

#203 Finished implementing and testing ContractTasks.

---

self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicesTestCase.java

PR for #209 
* Added Invoices.getById
* Removed invoices.isPaid
* Added paymentTime and transactionId as ctor paramters for a StoredInvoice
* An Invoice is considered paid when paymentTime != null && transactionId != null

#209 Invoices.getById(...) and removed Invoices.isPaid(...)

---

self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java

#208 Implemented equals and hashCode contracts for Stored* classes.

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/ContractInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/ContractInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

PR for #184 
* Extracted ContractInvoices in its own class
* Finished methods implementation (createNewInvoice(...) and active())
* Wrote unit tests for the whole class

#184 ContractInvoices extracted, finished implementation and tested

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTask.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTasks.java
self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/InvoiceTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/InvoiceTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

PR for #216 
Implemented and tested ``InvoiceTasks``
Implemented, tested and made use of ``StoredInvoicedTask``.
Left puzzle in Task.java.

Finished implementing Invoices and InvoicedTasks

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

PR for #220 
* Implemented and tested Task.value() and Task.estimation()
* Used the Task's actual value when registering it to an Invoice (InMemoryInvoicedTasks)

#220 Task.value() and Task.estimation()

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

PR for #207
Implemented Tasks.ofContract everywhere.
Left puzzle for writing unit tests.

#207 Tasks.ofContract implemented everywhere. Puzzle for unit testing

---

self-api/src/main/java/com/selfxdsd/api/Invitation.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java

PR for #225 
GithubInvitation implemented.
It is now possible to check the repo invitations and accept them automatically (the PMs will do that).

#225 GithubInvitation implemented and tested manually

---

self-api/src/main/java/com/selfxdsd/api/Self.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

Fixes #229 
Self is now AutoCloseable and closes the underlying Storage on close.

#229 Self extends AutoCloseable + unit test

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java

PR for #234 
* Added JsonResources.get(URI, accessToken)
* Used JsonResources inside GithubRepoInvitations
* Updated puzzle

#234 JsonResources.get(URI, accessToken) + use in GithubRepoInvitations

---

self-api/src/main/java/com/selfxdsd/api/Comment.java
self-api/src/main/java/com/selfxdsd/api/Comments.java
self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubComment.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommentTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueCommentsITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

PR for #100 
- added Comments::Issue.comments()
- created and tested GithubComment
- started implementing GithubIssueComments
Left puzzle to finish implementing and testing GithubIssueComments

#100 Comment/Comments API.

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java

PR for #237 
* Implemented and tested JdkHttp.post
* Implemented JsonResponse (implements Resource).

#237 JdkHttp.post + integration test

---

self-api/src/main/java/com/selfxdsd/api/Comments.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueCommentsITCase.java

PR for #244 
Left puzzle for GithubIssueComments pagination.

#244 Finished implementing and testing GithubIssueComments.

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java

PR for #252 
Implemented and tested the patch method.

#252 JsonResources.patch implemented

---

self-api/src/main/java/com/selfxdsd/api/Language.java
self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/English.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/EnglishTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/resources/commands_en.properties
self-core-impl/src/test/resources/responses_en.properties

Fixes #256 
Added the Language, spoken in a Project. 
English is the default language we'll be using at first. 
Added unit tests for English.

#256 Language, English, Project.language() + unit tests

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

Adds unit test for Tasks.ofContract() of the class ProjectTasks

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/main/java/com/selfxdsd/core/Resource.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResourcesTestCase.java

#254 Implemented and tested MockJsonResources.

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java

Adds unit test for Tasks.ofContract() of the class ContributorTasks

---

self-core-impl/src/main/java/com/selfxdsd/core/DoNotRepeat.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubComment.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java
self-core-impl/src/test/java/com/selfxdsd/core/DoNotRepeatTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

fixes #265 
DoNotRepeat implemented and unit tested
Used inside GithubIssue.comments()

#265 Implemented and used DoNotRepeat

---

self-core-impl/src/main/java/com/selfxdsd/core/AccessToken.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/AccessTokenTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResourcesTestCase.java

- Github and Gitlab AccessToken implemented and tested.
PR for #242

#242 AccessToken core-impl.

---

self-api/src/main/java/com/selfxdsd/api/Self.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

#268 Self.projects() + unit test

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

Fixes #270 
Started implementing Project.resolve()
Left puzzle to continue in a further ticket
Removed Project.webHookToken() because there's actually no need to expose it.

#270 Project.resolve(), unit test, todo

---

self-api/src/main/java/com/selfxdsd/api/Organizations.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganization.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganizations.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubOrganizationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubOrganizationsTestCase.java

- Left puzzle to implement and test Github Org repos.
PR for #259

#259 Implemented and tested Github Org/Orgs.

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganization.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganizations.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubOrganizationReposTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubOrganizationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubOrganizationsTestCase.java

#275 Implemented and tested GithubOrganizationRepos.

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/resources/responses_en.properties

PR for #272 
The PM can now handle the "newIssue" event.
It will register a new Task and leave a comment in the Issue.

#272 Issue.author(), PM.newIssue(...) and unit tests

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganizations.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubOrganizationsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryUsers.java

- implemented and tested(where needed) organizations in User implementations.
- moved organizations uri logic from Github to GithubOrganizations.
Left puzzle to start implementing Gitlab organizations (groups).
PR for #277

#277 Added Organizations to User API.

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/resources/responses_en.properties

PR for #284 
Implemented and unit tested PM.reopenedIssue.

#284 StoredProjectManager.reopenedIssue

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

#286 ProjectTasks works with Stream<Task> supplier.

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java

#294 StoredContract.value + unit test

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganization.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizations.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationsTestCase.java

- implemented and tested.
- updated puzzle.
PR for #285

#285 GitlabOrganizations/GitlabOrganization.

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganization.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationReposTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationTestCase.java

- implemented and tested.
- left puzzle for gitlab invitations.
PR for #298

#298 Implemented GitlabOrganizationRepos.

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/ContractInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

Fixes #301 
Invoice now can return its contract.
updated tests and constructor of StoredInvoice.

#301 Invoice.contract() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

- implemented and tested (hardcoded 60 min. for now).
- left puzzle for Labels API.
PR for #300

#300 Issue estimation.

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#306 StoredTask ctor with estimation

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryUsers.java

#309 removed User.organizations()

---

self-api/src/main/java/com/selfxdsd/api/InvoicedTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/InvoiceTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/InvoiceTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java

#313 InvoicedTasks.ofInvoice(...) expects Invoice

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/InvoiceTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/InvoiceTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java

Fixes #315 
Also left puzzle for implementing ``Invoice.register(Task)``.

#315 InvoicedTasks,register expects Invoice

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

#319 Project.webHookToken() + unit test

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

#320 Removed secret param from Project.resolve(...)

---

self-api/src/main/java/com/selfxdsd/api/pm/Intermediary.java
self-api/src/main/java/com/selfxdsd/api/pm/PreconditionCheck.java
self-api/src/main/java/com/selfxdsd/api/pm/Step.java

Fixes #324 
Added the Steps infrastructure and left TODO to continue work.

#324 pm Step, Intermediary and PreconditionCheck

---

self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResourcesTestCase.java

fixes #328
* Collaborators scaffolding
* JsonResources.put(...) implemented and unit tested
* Left puzzle to continue work

#328 Started implementing Collaborators

---

self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/GithubCollaborators.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCollaboratorsTestCase.java

PR for #331 
* Implemented GithubCollaborators.invite
* added logging
* Added the ``permission`` parameter
* Wrote unit tests.

#331 GithubCollaborators.invite implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java

#334 Updated JsonResources request body to JsonValue.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorsTestCase.java

#330 GitlabCollaborators implemented and tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java

#330 GitlabCollaborators - removed puzzle.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationReposTestCase.java

#343 Create gitlab organization repo from json.

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/pm/Step.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/InvitePm.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#327 InvitePm scaffolding + puzzles

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/InvitePm.java

#349 Constants for provider access levels

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/InvitePm.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/InvitePmTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java

PR for #350 
* Added and tested ProjectManager.userId()
* Addapted InvitePm to use the userId in case of GitLab
* Wrote unit tests for InvitePm

#350 InvitePm finished and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/SetupWebhook.java

#348 SetupWebhook scaffolding + puzzle

---

self-api/src/main/java/com/selfxdsd/api/Webhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/SetupWebhook.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/SetupWebhookTestCase.java

PR for #355 
* Implemented Webhooks interface
* Left puzzle for GitlabWebhooks.
* Implemented and used GithubWebhooks
* Left puzzle for implementing GithubWebhooks.add(...)

#355 Webhooks implemented and tested + puzzles

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubWebhooksTestCase.java

#358 GithubWebhooks.add(...) implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/AuthenticatedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

PR for #290 
Adds unit test for Authenticated and adds puzzle for PmUser.

Adds unit test for Authenticated and adds puzzle for PmUser

---

self-api/src/main/java/com/selfxdsd/api/storage/Paged.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/ProjectsPaged.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

- fixed a bug in ProjectsPaged#totalPages where total pages were not rounded up.
- updated puzzle to write test for UserProjects and InMemoryProjects.
- added puzzle to implement paging for remaining Self entities.
PR for #353

#343 Unit tested PmProjects.

---

self-api/src/main/java/com/selfxdsd/api/storage/Paged.java
self-core-impl/src/main/java/com/selfxdsd/core/BasePaged.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

- prepared filtered classes to use streams for future using of Paged api.
- updated unit tests.
- refactored ProjectsPaged into a base class.
- updated puzzle to be more specific about which resources need to support paging and how to implement it.
PR for #364

#364 Updated storage filtered classes to use streams.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabWebhooksTestCase.java

#357 GitlabWebhooks implemented + tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Pr for #363. Modified PmUser to be package private, is this wanted or should I stick to @criske 's advice to @ANadrowski testing the PmUser indirectly?

#363 Added tests for PmUser 

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java

#326 fixed javadoc problem

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

fixes #376
* Implemented Wallet interface and the Missing wallet + tests
* Implemented Project.wallet() + test (at the moment it always returns the Missing wallet).
* Left puzzles to continue work in future tasks.

#376 Wallet, Missing wallet, Project.wallet()

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java

#379 ProjectContributors encapsulates the Project

---

self-core-impl/src/main/java/com/selfxdsd/core/BasePaged.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java

- added test to reflect the fix.
Fixes for #374

#374 Fixed totalPages bug in BasePaged.

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/exceptions/InvoiceAlreadyPaidExeption.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

PR for #384 
* Implemented and tested Wallet.pay in Missing
* Added InvoiceAlreadyPaidException
* Added and tested accessor methods Invoice.paymentTime() and Invoice.transactionId()

#384 Wallet.pay implemented in Missing and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

Unit tests for equals and hashcode methods for each Stored classes

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResourcesTestCase.java

- added + tested MockRequests::MockJsonResources#requests()
PR for #389

#389 Added a way to test requests with MockJsonResources.

---

self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/ContractInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/ContractInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

Fixes #386 
Implemented and tested Invoices.registerAsPaid(Invoice).

#386 Invoices.registerAsPaid implemented

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java

Fixes #393 
Left puzzles to update the election algorithm and also to expect the commission when registering a new PM.

#393 PM.commission() implemented, tested + puzzles

---

self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java

#395 ProjectManagers.register(...) addapted to accept the commission

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java

#398 StoredContract.value() adds up the PM's commission too

---

self-api/src/main/java/com/selfxdsd/api/InvoicedTask.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/InvoiceTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/InvoiceTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java

Fixes #400 
* Save PM Commission in the InvoicedTask
* Added methods InvoicedTask.commission() and InvoicedTask.totalAmount() + tests
* Left puzzle to also adapt Invoice.register(Task);

#400 Register PM commision in new InvoicedTask

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java

#396 Electing uses PM's commission too.

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

#403 Invoice.register() now accepts the commission as well

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java

#404 Checks ProjectContributors project eq. Task's project.

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

PR for #410 
Also left puzzle to remove the first constructor, because it's not actually needed.

#410 StoredInvoice encapsulates its tasks

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

PR for #412 
Removed unused constructor.

#412 StoredInvoice: removed useless constructor

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java

PR for #418 
Started with handling the event of unassigned tasks. 
Left puzzle to continue work after we have a way of assigning a task to a contributor.

#418 Started Handling Unassinged Tasks

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

Fixes #420 
puzzle to refactor some tests.

#420 StoredTask.issue gets the PM's Issue

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/English.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#423 rewrote tests to use only mocks

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java

PR for #421 
Implemented methods assign and unassign for the GithubIssue.
Wrote tests.

#421 Github Issue.assign and unassign methods

---

self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java

#421 Scaffolding for Task.assign, left puzzle

---

self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java

PR for #427 
Method implemented in StoredContributor and tested.

#427 Contributor.contract(...) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

PR for #430 
Method implemented in all implementations of ``Tasks``. Maybe some of those implementations should do some additional checks (to maintain the context), but let's leave that for later.

#430 Tasks.assign(Task, Contract, days) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

PR for #428 
Finished implementing and testing method StoredTask.assign(...).
The return type was changed to ``Task``, to return the assigned Task.

#428 StoredTask.assign(...) finished and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/resources/responses_en.properties

PR for #421 
Finished implementation.
Also added logging and unit tests.

#421 StoredProjectManager.unassignedTasks(Event) finished

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#435 assign Issue as well

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#437 StoredTask.issueId() implmeneted and tested

---

self-api/src/main/java/com/selfxdsd/api/pm/Conversation.java

fixes #441 
Started sketching out the Conversation, left puzzle.

#441 sketch of Conversation + puzzle

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/InvitePm.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/SetupWebhook.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/InvitePmTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#444. Removed Event.provider()

---

self-api/src/main/java/com/selfxdsd/api/Language.java
self-api/src/main/java/com/selfxdsd/api/pm/Conversation.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Understand.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnderstandTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/EnglishTestCase.java

PR for #446 
The Understand conversation is implemented and tested.
Left puzzles for Hello/Confused conversations, as well as the SendReply step.

#446 Implemented and tested Understand

---

self-api/src/main/java/com/selfxdsd/api/Comment.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubComment.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/SendReply.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Understand.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommentTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/SendReplyTestCase.java

PR for #449 
Implemented and tested Comment.author();
Implemented and tested SendReply;

#449 SendReply implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Hello.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/SendReply.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/HelloTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/SendReplyTestCase.java

#450 Hello conversation implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/Resign.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/ResignTestCase.java
self-core-impl/src/test/resources/commands_en.properties

#454 Resign partially implemented, tested and puzzles

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Confused.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Understand.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/ConfusedTestCase.java
self-core-impl/src/test/resources/responses_en.properties

#451. Confused implemented + tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorIsAssignee.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Resign.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AuthorIsAssigneeTestCase.java

PR for #457 
AuthorIsAssignee step implemented and tested.
Left puzzle to continue work.

#457 AuthorIsAssignee implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorIsAssignee.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Resign.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/UnassignTask.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnassignTaskTestCase.java
self-core-impl/src/test/resources/responses_en.properties

PR for #459 
Implemented and tested the UnassignTask step.
Finished composition or steps inside Resign.start.

#459 UnassignTask implemented; Resign composition finished

---

self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java

- tested InMemoryTasks assign() + unassign().
PR for #443

#443. InMemoryTasks assign()+unassign() using Task#issueId().

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Resign.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Status.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StatusTestCase.java
self-core-impl/src/test/resources/commands_en.properties
self-core-impl/src/test/resources/responses_en.properties

PR for #464 
When a user says "status" the PM will reply with 3 possibilities: 
1. The Task is not registered
2. The Task is registered but not yet assigned to anyone
3. The Task is assigned to X since Y, until Z, with estimation E.

#464 Status conversation implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorHasRoles.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Deregister.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/RemoveTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AuthorHasRolesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/DeregisterTestCase.java
self-core-impl/src/test/resources/commands_en.properties
self-core-impl/src/test/resources/responses_en.properties

- implemented and tested AuthorHasRoles step.
- implemented Deregister conversation.
- mostly implemented RemoveTask step.
- left puzzle to test Deregister,RemoveTask + finish it.
- left puzzle to remove a task from db.
PR for #466

#466. Deregister Conversation mostly implemented.

---

self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

#478. Replaced Tasks#getById() issue() call w/ issueId()&projcect().

---

self-api/src/main/java/com/selfxdsd/api/exceptions/RepoNotFoundException.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java

#480 RepoNotFoundException implemented and used

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java

#477 withToken maintains the Authenticated User

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorHasRoles.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AuthorHasRolesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RegisterTestCase.java

Fixes #470
Started implementing the Register conversation. Left puzzle to continue.
Addapted AuthorHasRoles to return true if the role is ``ANY``.
Unit tests.

#470 Register scaffolding, AuthorHasRoles ANY + unit tests

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/TaskIsRegistered.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RegisterTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/TaskIsRegisteredTestCase.java
self-core-impl/src/test/resources/commands_en.properties
self-core-impl/src/test/resources/responses_en.properties

PR for #487 
Also added more scaffolding to ``Register``, unit tests and puzzle for final step (actually registering the Issue as a Task).

#487 TaskIsRegistered implemneted and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/RegisterIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RegisterIssueTestCase.java
self-core-impl/src/test/resources/responses_en.properties

PR for #489 
Implemented and tested step "RegisterIssue" and finished composition of steps inside Register.

#489 RegisterIssue implemented, tested and used

---

self-api/src/main/java/com/selfxdsd/api/Resignation.java
self-api/src/main/java/com/selfxdsd/api/Resignations.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryResignations.java

Fixes #462 
Impelmented resignations + in-memory resignations. 
Left puzzle for TaskResignations.

#462 Resignations + InMemoryResignations

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/TaskResignations.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryResignations.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/TaskResignationsTestCase.java

PR for #496 
Also implemented InMemoryResignations.ofTask.

#496 TaskResignations implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/Wallets.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/ProjectWallets.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/ProjectWalletsTestCase.java

Fixes #499 
Implemented wallets storage api + inmemory wallets
left puzzles.

#499 Implemented wallets infrasturcture

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java

PR for #502 
Implemented Wallet.cash(), Wallet.debt() and Wallet.available()
Wrote unit tests.

#502 Wallet.cash()/available()/debt() + unit tests

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

PR for #503 
Added method Project.wallets() which reads the wallets from the storage.
Modified method Project.waller() to return the active wallet.

#503 Project reads wallets and active wallet from storage

---

self-api/src/main/java/com/selfxdsd/api/Wallets.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/ProjectWallets.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/ProjectWalletsTestCase.java

#508 ProjectWallets.activate(Wallet) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Resignations.java
self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredResignation.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/TaskResignations.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryResignations.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredResignationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/TaskResignationsTestCase.java

#498. Implementend+tested Resignations#register.

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#511. Task#resignations() and adapted it to task elect algorithm.

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java

Fixes #510 
When we activate a Repo, we assign the Project a fake wallet with $10M in it.

#510 Add fake Wallet when registering a new Project

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/Wallets.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/ProjectWallets.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/ProjectWalletsTestCase.java

#514 Wallets.register(...) expects String identifier

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/AuthenticatedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java

#519 User.contracts() implemneted and tested

---

self-api/src/main/java/com/selfxdsd/api/exceptions/InvoiceException.java
self-api/src/main/java/com/selfxdsd/api/exceptions/RepoException.java
self-api/src/main/java/com/selfxdsd/api/exceptions/SelfException.java

#131. Self Exceptions.

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

PR for #527 
Implemented and tested Issue.close()
Bonus: also implemented and tested Issue.reopen()

#527 Implemented Issue.close() and Issue.reopen()

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ContractsException.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java

PR for #530 
- left puzzle for Contributors self exceptions.

#530. Contracts Self exceptions.

---

self-api/src/main/java/com/selfxdsd/api/PayoutMethod.java
self-api/src/main/java/com/selfxdsd/api/PayoutMethods.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryPayoutMethods.java

Fixes #531 
Implemented the interfaces;
Started implementing the InMemoryPayoutMethods;
Left puzzle to continue.

#531 PayoutMethods Implementation Start

---

self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-api/src/main/java/com/selfxdsd/api/PayoutMethod.java
self-api/src/main/java/com/selfxdsd/api/PayoutMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryPayoutMethods.java

PR for #538 
Left puzzles to continue work.

#538 StripePayoutMethod implemented and tested + puzzles

---

self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/AuthenticatedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java

PR for #544 
Removed User.contracts()
Implemented and tested User.asContributor()

#544 User.asContributor() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ContributorsException.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java

#534. Contributors Self exceptions.

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ProjectsException.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java

PR for #546 
- left puzzle for Tasks SelfExceptions.

#546. SelfExceptions for Projects.

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/Self.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java

PR for #521 
- left puzzle for Contributors#ofProvider()

#521. Self API contributors().

---

self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/Task.java
self-api/src/main/java/com/selfxdsd/api/exceptions/TasksException.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

- removed puzzle for SelfExceptions Projects
- added puzzle for SelfExceptions Invoices.
PR for #549

#549. SelfExceptions for Tasks.

---

self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java

#551 Contributor.payoutMethods() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ContributorsException.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProviderContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProviderContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java

#550. ProviderContributors implemented+tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java

#557 renamed stripe.api.token to self_stripe_token

---

self-core-impl/src/main/java/com/selfxdsd/core/Env.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java

#560 Env constants class for env variables

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java
self-core-impl/src/test/resources/responses_en.properties

fixes #562 
* Implemented and tested the assignedTasks review method
* Implemented and tested Issue.isClosed()
* Implemented and tested Task.contracT()

#562 PM.assignedTasks(Event) implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java

#565 removed slash and logging

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#568. Check for closed Issue when reviewing Unassigned Tasks

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#572. Takes into account minutes when checking for missing deadline.

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/pm/Conversation.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java

#570 issue_comment event resolved and PM.comment implemented

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-api/src/main/java/com/selfxdsd/api/pm/Conversation.java
self-core-impl/src/main/java/com/selfxdsd/core/IgnoreBots.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/IgnoreBots.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/IgnoreBotsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java

PR for #576 
* Ignore comments coming from other PMs
* Ignore comments coming from some known chatbots
* Handle only comments which start with ``@[pm username]``.
* unit tests
* Used IgnoreBots in conversation composition.

#576 IgnoreBots implemented, teste and used

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java

#578 register resignation, then resign

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubWebhooksTestCase.java

#583 issue_commnet and pull_request Webhook events

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/UnassignTask.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnassignTaskTestCase.java

#589 UnassignTask registers resignation too.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/Status.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StatusTestCase.java
self-core-impl/src/test/resources/responses_en.properties

#591 Status cmd message for unreg task & issue closed.

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/exceptions/WalletAlreadyExistsException.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java

Fixes #581 
Left puzzle to continue with Customer Stripe creation.
Left puzzle for unassignedTasks logic.

#581 Project.createStripeWallet scaffolding + puzzles

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#595 Assign Task to Issue assignee or new elect.

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

PR for #594 
A Stripe Customer is created for each Project and associated with the project's Wallet.
Left puzzles to continue work on updating the Wallet's limit and implementing the Wallets payment methods.

#593 StoredProject.createStripeWallet implemented + puzzles

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/resources/responses_en.properties

Fixes #585 
* Estimation 30min for PR and 60min for Issue
* Updated openIssue and reopenedIssue events with diff. replies for PR/Issue
* Updated assignIssue comment 
* Deadline for Issue tasks: 10 days; dedline for PRs: 3 days.

#585 Handling PRs

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

#604 StripeWallet implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Issues.java
self-core-impl/src/main/java/com/selfxdsd/core/FoundIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/FoundIssuesTestCase.java

Fixes #610 
Started with scaffolding.
Implemented FoundIssues + unit tests.
Left puzzle to continue work.

#610 Issues.search scaffolding. FoundIssues + unit tests

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java

#612 GithubIssues.search(...) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/PaymentMethod.java
self-api/src/main/java/com/selfxdsd/api/PaymentMethods.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/exceptions/PaymentMethodsException.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredPaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredPaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

PR for #598
- left puzzle for PaymentMethods#ofWallet

#598 PaymentMethods API and StoredPaymentMethod.

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/exceptions/WalletPaymentException.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredPaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

#606 Implemented and tested Wallet#pay().

---

self-api/src/main/java/com/selfxdsd/api/PaymentMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/WalletPaymentMethods.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/WalletPaymentMethodsTestCase.java

#615 Implemented and tested WalletPaymentMethods.

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

#616 equals and hashcode for Wallet

---

self-api/src/main/java/com/selfxdsd/api/Label.java
self-api/src/main/java/com/selfxdsd/api/storage/Labels.java
self-core-impl/src/main/java/com/selfxdsd/core/FoundIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubLabel.java
self-core-impl/src/test/java/com/selfxdsd/core/FoundIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubLabelTestCase.java

#588 Implemented and tested GithubIssueLabels.

---

self-api/src/main/java/com/selfxdsd/api/exceptions/ContractsException.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ContributorsException.java
self-api/src/main/java/com/selfxdsd/api/exceptions/InvoiceException.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ProjectsException.java
self-api/src/main/java/com/selfxdsd/api/exceptions/TasksException.java

#634 Fixed json patching for SelfException impls.

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ContractsException.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

Fixes #625 
Implemented Contract.update(hourlyRate)
Implemented and tested Contracts.update(Contract, hourlyRate)

#625 implementd Contract.update(horlyRate)

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/exceptions/ContractsException.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ProjectContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java

Fixes #636 
A contract can now be marked for removal.
After a certain period of time, it will be removed for good.

#636 Mark Contract for Removal

---

self-api/src/main/java/com/selfxdsd/api/Repo.java
self-api/src/main/java/com/selfxdsd/api/Stars.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubStars.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubStarsTestCase.java

Repo Star for github #630

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubStars.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubStarsTestCase.java

#641 Tested GithubStars#add.

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java

#640 do not elect contracts marked for removal

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubInvitationTestCase.java

#629 Added starring to GithubInvitation#accept + tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StatusTestCase.java

#649 Add PO Contract When Activating Repo.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java

#652 unassign Issue on invoiced task or missed deadline

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/RegisterResignation.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Resign.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RegisterResignationTestCase.java

Fixes #653 
UnassignTask does not register the resignation anymore. 
Implemented and tested RegisterResignation.
Used RegisterResignation in the Resign flow.

#653 RegisterResignation implemented, tested and used in Resign

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Understand.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnderstandTestCase.java

#656 added Commit :: Event.commit()

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

#660 GithubIssue.repoFullName() from url attribute

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java

#662 throw ISE if no PM is found

---

self-api/src/main/java/com/selfxdsd/api/Commit.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCommit.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitTestCase.java

#664 Commit.shaRef() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/SelfTodos.java
self-core-impl/src/main/java/com/selfxdsd/core/RestfulSelfTodos.java
self-core-impl/src/test/java/com/selfxdsd/core/RestfulSelfTodosTestCase.java

#667 RestfulSelfTodos implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java

#670 Customer name, description and email

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

#666 Issue.body() implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/RestfulSelfTodos.java
self-core-impl/src/test/java/com/selfxdsd/core/RestfulSelfTodosTestCase.java

#674 catch and log ISE in RestfulSelfTodos.post(...)

---

self-api/src/main/java/com/selfxdsd/api/Commits.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCommits.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitsTestCase.java

Per #673 
- Remove method and its usage

#673: Remove method Commits#received

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Labels.java
self-api/src/main/java/com/selfxdsd/api/Repo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/WithContributorLabel.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/WithContributorLabelTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/IssueHasLabelTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

PR for #691 
Implemented and tested GithubRepoLabels;
Implemented and tested Repo.labels();
Added puzzle to use GithubRepoLabels inside GithubIssueLabels.add(...) in order to register the repo with a random color;

#691 GithubRepoLabels implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueLabels.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueLabelsTestCase.java

#694 register label in repo before adding it to the issue

---

self-api/pom.xml
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredPaymentMethodTestCase.java

#696 implemented Wallet.paymentMethodSetupIntent()

---

self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java

Per #686 
- Add method `remove`

#686: Add `Contracts#remove(Contract)`

---

self-api/src/main/java/com/selfxdsd/api/PaymentMethod.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredPaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripePaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/MissingWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

Fixes #700 
Implemented and tested Wallet.identifier();
Added method PaymentMethod.json() and made class StoredPaymentMethod abstract;
Implemented and tested StripePaymentMethod.json() (StripePaymentMethod extends StoredPaymentMethod to provide impl for method json);

#700 implemented PaymentMethod.json()

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java

Fixes #687 
Implemented StoredContract.remove();
Added unit tests for it;

#687 Contract.remove() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Commits.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCommits.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitsTestCase.java

#703 GithubCommits.latest() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/pm/Intermediary.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Resign.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/ResignTestCase.java

#688: Change order of steps during asked resignation

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/HelloIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/StarRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubInvitationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/HelloIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StarRepoTestCase.java

Fixes #707 
Implemented and tested GithubInvitation.repo();
Pulled out and tested StarRepo decorator for an Invitation;
Implemented and tested HelloIssue decorator for an Invitation;
Used the 2 decorators over GithubInvitation (GithubInvitations.iterator());

#707 'Hello' Issue after Accepting Invitation

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

Fixes #709 
Added and tested Invoice.commission();
Revised StripeWallet.pay(...) to comply with https://stripe.com/docs/connect/collect-then-transfer-guide

#709 StripeWallet.pay(...) implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java

#714 100k for the Fake Wallet

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java

#717 Started implementing GitlabIssues.

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java

#731 FakeWallet updates its cash to storage.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

#722 Implemented + test GitlabIssue#assign.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabLabel.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoLabels.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabLabelTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

For #727 
Implemented and tested GitlabRepoLabels (returned by GitlabRepo.labels());
Implemented and tested GitlabIssueLabels (returned by GitlabIssue.labels());

#727 GitLab Labels Implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubWebhooksTestCase.java

#742 specify push on Github Webhook

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java

#745 Contract.restore() implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

#724 GitlabIssue.close() implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java

#750 PmProjects initial page is now Page.all().

---

self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-api/src/main/java/com/selfxdsd/api/Contracts.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-api/src/main/java/com/selfxdsd/api/Webhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

PR for #681 
Implemented and tested Project.deactivate();
Implemented and tested Projects.remove(Project);
Left puzzles for Collaborators.remove(username) and Webhooks.remove();

#681 Project deactivation/removal imlemented

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubCollaborators.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCollaboratorsTestCase.java

#758 GithubCollaborators#remove(username) implemented + tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

Fixes #763 
Added more logging to StripeWallet.pay();
Added description to Stripe's PaymentIntent;

#763 Stripe description and more logging

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

#757 GitlabCollaborators.remove(...) implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabStars.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabStarsTestCase.java

#716 Implement GitlabStars

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

PR for #770 
We expect the (authenticated) Repo as parameter because Project.repo() will return an unauthenticated Repo in this scenario.

#770 Project.deactivate() expects Repo

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabWebhooksTestCase.java

PR for #756 
We iterate over existing webhooks and remove the ones which contain ``//self-xdsd.`` in the URL.

#756 Implemented and tested GitlabWebhooks.remove()

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java

#728 GitlabIssues#getById() implemented + tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java

#778 Fixed bug where GitlaIssues#getById returned GithubIssue.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java

#775 GitlabIssues.received() impl & test

---

self-core-impl/src/test/java/com/selfxdsd/core/projects/EnglishTestCase.java
self-core-impl/src/test/resources/commands_en.properties
self-core-impl/src/test/resources/responses_en.properties

#781 links in responses and new command options

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoLabels.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

PR for #776 
* Implemented and tested GitlabIssues.open(...)
* Implemented and tested GitlabRepo.issues()
* Removed unnecessary ``Repo`` from GitlabRepoLabels

#776 GitlabIssues.open(...) implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

#725 GitlabIssue.reopen() implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueLabels.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

#723 GitlabIssue.unassign(...) implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java

#777 Implemented + tested GitlabIssues#search(...).

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java

#790 GithubIssues#search() has text and labels encoded.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/AssignTaskToIssueAssignee.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AssignTaskToIssueAssigneeTestCase.java

Fixes #795 
Add contributor label when an Issue is assigned directly at opening.

#795 add contributor label on direct task assignment

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java

#801 UserProjects Page.all()

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommit.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommits.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

#806 Gitlab commits implementation 

---

self-api/src/main/java/com/selfxdsd/api/BillingInfo.java
self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

Fixes #803 #804 
Introduced Project.billingInfo and Contributor.billingInfo;
Project.createStripeWallet sends BillingInfo with to Stripe (in the Customer object);
Left puzzles;

#803 BillingInfo for Project and Contributor

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/CustomerBillingInfo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/CustomerBillingInfoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

Implemented and tested Wallet.billingInfo();
Project takes its BillingInfo from the active Wallet;
StripeWallet reads the BillingInfo from the Customer;
Added tests;

#812 Implemented Project.billingInfo()

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/AccountBillingInfo.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java

PR for #813
Implemented and tested PayoutMethod.billingInfo();
Implemented and tested Contributor.billingInfo();
Left puzzle to complete the implementation of AccountBillingInfo;

#813 Contributor.billingInfo() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/BillingInfo.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/AccountBillingInfo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/CustomerBillingInfo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/CustomerBillingInfoTestCase.java

Fixes #819 
BillingInfo now has the isCompany flag;
If isCompany then it should have a legalName;
if !isCompany then it should have firstName + lastName;
Added taxId attribute.

#819 BillingInfo for individual or company and taxId

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/AccountBillingInfo.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/AccountBillingInfoTestCase.java

#817 AccountBillingInfo implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/AccountBillingInfo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/CustomerBillingInfo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java

Fixes #830 
BillingInfo.other is optional both when creating and when reading Stripe data.

#830 BillingInfo.other is optional

---

self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java

#823 Add tests for GitlabIssueComments post() & received()

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

#833 Payment Possible Only Over 108 Euros.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabComment.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommentTestCase.java

Fix for #839 
No payment for this one :)

#839 author.username instead of author.name

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommitComments.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitCommentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitTestCase.java

#809 GitlabCommit & GitlabCommitComments impl & tests

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Fixes #844 
Using only longValue, to avoid arithmeticexception.

#844 longValue

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

Fixes #846 
Compare totalAmount (including the PM's commission).

#846 totalAmount

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Fixes #848 
Handle StripeExceptions for cases when authentication is required or card is declined (not enough funds).

#848 handle authentication_required and no_funds

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/Country.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Fixes #853 
Implemented the VAT rules. If applicable, VAT will be deducted from the Contributor's amount.
Left puzzle to write the VAT amount on the Invoice as payment indicator.

#853 VAT from Contributor implemented

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

Fixes #858 
Left puzzle to continue with the modification of method Invoices.registerAsPaid(...).

#858 revert changes made in #855

---

self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorsTestCase.java

#859 add tests for GitlabCollaborators.iterator()

---

self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/ContractInvoices.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/ContractInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

PR for #867 
Modified the method to also accept the contributor's VAT.
Left puzzle to implement the PlatformInvoice.

#867 Invoices.registerAsPaid(...) accepts contributorVat

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/PlatformInvoice.java
self-api/src/main/java/com/selfxdsd/api/PlatformInvoices.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredPlatformInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredPlatformInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

PR for #886 
Implemented PlatformInvoices and PlatformInvoice.
Implemented and tested StoredPlatformInvoice.
Implemented and tested Invoice.platformInvoice().
Added puzzle for method ``toPdf(...)``

#886 PlatformInvoices implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/StoredPlatformInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredPlatformInvoiceTestCase.java

#897 StoredPlatformInvoice eurToRon constructor param

---

self-api/src/main/java/com/selfxdsd/api/Self.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

#903 core.platformInvoices

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

(#895) Accept `OutputStream` instead of returning `File`

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

#909 Implemented+tested "GitlabIssue#comments()".

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/XmlBnr.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/XmlBnrTestCase.java

#914 tests for XmlBnr

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabWebhooksTestCase.java

fixes #927 
Added all the needed events to the GitLab Webhook.

#927 appropriate webhook events for GitLab

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueLabels.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueLabelsTestCase.java

#929 GitlabIssueLabels is array of String, not JsonObject

---

self-api/src/main/java/com/selfxdsd/api/Repo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

#932 Repo.pullRequests() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryResignations.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#933 Added `isPullRequest` flag for a `Task` to be stored.

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#937 StoredTask.issue() differenciates between Issue and PR

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

#939 Generic GitlabIssue#findUserId().

---

self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/AssignTaskToIssueAssignee.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorIsAssignee.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/RegisterResignation.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/RemoveTask.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Status.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/TaskIsRegistered.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/UnassignTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AssignTaskToIssueAssigneeTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AuthorIsAssigneeTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/DeregisterTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RegisterResignationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RemoveTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StatusTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/TaskIsRegisteredTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnassignTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

Fixes #942 
Modified Tasks.getById(...) and related implementations.
Modified code using Tasks.getById(...).
Updated unit tests.

#942 Task.isPullRequest part of the Task PK

---

self-api/src/main/java/com/selfxdsd/api/Self.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java

#948 Self.authenticate(personalAccessToken) declared + todo

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

Fixes #954 
Also added unit test.

#954 GitlabIssue.isClosed() checks for merged state

---

self-api/src/main/java/com/selfxdsd/api/Admin.java
self-api/src/main/java/com/selfxdsd/api/Self.java
self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

PR for #946 
- Admin interface created.
- platformInvoices moved from Self to Admin
- unit test updated

platformInvoices() moved to the Admin responsibility.

---

self-api/src/main/java/com/selfxdsd/api/Admin.java
self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/AuthenticatedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

PR for #959 
Implemented and tested StoredUser.asAdmin();
PR for #958 
Implemented and tested method asAdmin in Authenticated and PmUser.

#959 User.asAdmin Implemented and Tested Everywhere

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/GithubWebhookEvent.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/GitlabWebhookEvent.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/WebhookEvents.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GithubWebhookEventTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GitlabWebhookEventTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/WebhookEventsTestCase.java

Fixes #926 
Ported and tested GithubWebhookEvent from self-pm/self-todos;
Ported and tested GitlabWebhookEvent from self-pm/self-todos;
Implemented and tested WebhookEvents factory;

#926 GithubWebhookEvenrt and GitlabWebhookEvent moved to Core

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/GitlabWebhookEvent.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GitlabWebhookEventTestCase.java

#963 cache Issue from GitlabWebhookEvent.issue() and tests

---

self-api/src/main/java/com/selfxdsd/api/ApiToken.java
self-api/src/main/java/com/selfxdsd/api/ApiTokens.java
self-api/src/main/java/com/selfxdsd/api/User.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredApiToken.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/AuthenticatedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredApiTokenTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

PR for #966, #967 #968
Added ApiTokens.getById(...);
Added Storage.apiTokens();
Implemented and tested ApiToken.owner();
Implemented and tested User.apiToken();
Removed puzzles.

Finished ApiTokens Scaffolding

---

self-api/src/main/java/com/selfxdsd/api/ApiTokens.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java

PR for #951 
Left 2 puzzles for register and remove methods in ApiTokens.

#951 BaseSelf.authenticate(token) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/ApiToken.java
self-api/src/main/java/com/selfxdsd/api/ApiTokens.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredApiToken.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredApiTokenTestCase.java

Implemented and tested ApiToken#remove() based on ApiTokens#remove(ApiToken).
pr for #973

#973 Implemented + tested ApiToken#remove().

---

self-api/src/main/java/com/selfxdsd/api/Provider.java
self-core-impl/src/main/java/com/selfxdsd/core/AccessToken.java
self-core-impl/src/main/java/com/selfxdsd/core/Bitbucket.java
self-core-impl/src/test/java/com/selfxdsd/core/AccessTokenTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketTestCase.java

Left puzzles for Repo, Invitations and Organizations implementations.
Pr for #943

#943 Started Implementing BitBucket.

---

self-api/src/main/java/com/selfxdsd/api/ApiTokens.java
self-api/src/main/java/com/selfxdsd/api/User.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseSelf.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/AuthenticatedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredUserTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Per #972 
- Add methods 
- Implement User's token registration

#972: Implement token registration 

---

self-core-impl/src/main/java/com/selfxdsd/core/Bitbucket.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganization.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganizations.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketOrganizationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketOrganizationsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketTestCase.java

PR for #978 
- BitbucketOrganizations implemented
- Unit tests updated

BitbucketOrganizations implemented

---

self-api/src/main/java/com/selfxdsd/api/PayoutMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ContributorPayoutMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ContributorPayoutMethodsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryPayoutMethods.java

PR for #988 
Left puzzle to add PayoutMethod.remove();

#988 PayoutMethods.remove(PayoutMethod) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/PaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripePaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/WalletPaymentMethods.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/WalletPaymentMethodsTestCase.java

PR for #993 
* StripePaymentMethod.remove() implemented and tested;
* WalletPaymentMethods.remove(PaymentMethod) calls PaymentMethod.remove();

#993 StripePaymentMethod.remove() implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

#995 SetupIntent creation: usage explicit off_session

---

self-api/src/main/java/com/selfxdsd/api/PaymentMethod.java
self-api/src/main/java/com/selfxdsd/api/PaymentMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredPaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/WalletPaymentMethods.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/WalletPaymentMethodsTestCase.java

Fixes #1002 
Implemented and tested PaymentMethods.deactivate(PaymentMethod);
Implemented and tested PaymentMethod.deactivate();
Added todo to fix flow in PaymentMethod activation;

#1002 PaymentMethod deactivation implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

PR for #1009 
StripeWallet.remove() modified to remove the Customer from Stripe before removing the Wallet from Self XDSD.

#1009 StripeWallet.remove() removes Customer from Stripe

---

self-core-impl/src/main/java/com/selfxdsd/core/Bitbucket.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketTestCase.java

- Implemented and tested `fullName()`.
- Left puzzles for the remaining BitbucketRepo methods.
PR for #976

#976 Started implementing BitbucketRepo.

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketCommit.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketCommits.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCommitTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCommitsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java

- Left puzzle for BitbucketCommit#comments.
PR for #1017

#1017 Implemented and tested BitbucketCommits/Commit.

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/Payment.java
self-api/src/main/java/com/selfxdsd/api/Payments.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredPayment.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

PR for #979
- Add Payment & Payments interfaces.
- Add StoredPayment implementation.
- StoredPayment doesn't contain any logic it's just a DTO so I don't know if it should be tested and how?

#979 Add Payment & Payments interfaces

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketComment.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketCommitComments.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCommentTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCommentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCommitTestCase.java

#1023 Implemented+tested BitbucketCommitComments & BitbucketComment.

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredPayment.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredPaymentTestCase.java

#1025 StoredPayment tested.

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

PR for #1027 
The StoredInvoice loads its Payments lazily from the Storage.

#1027 Invoice.payments() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Payments.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/InvoicePayments.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/InvoicePaymentsTestCase.java

#1040 InvoicePayments implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java

#1012 BitbucketRepo::activate() impl & test

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java

#1014 BitbucketRepo::collaborators() impl & test.

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/PreCheckPayments.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Revised messages of this exception because they will be saves as Payment failureReason and displayed to both the PO and the Contributor.

#1049 Better messages for WalletPaymentException

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java

PR for #1013
I think this PR is relatively big :( , because I found myself required to fill some gaps to keep the code consistent :)

#1013 Start implementing BitbucketRepo::issues()

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketWebhooksTestCase.java

#1052 Finished testing BitbucketWebhooks.

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketStars.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketStarsTestCase.java

#1016 BitbucketStars placeholder implementation.

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketRepoTestCase.java

#1067 Placeholder for Bitbucket Labels.

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTask.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProviderContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java

Fixes #1073 
The ProjectManager now encapsulates the contributorCommission;
Unit tests;
Renamed original commission to projectCommission;
Left puzzles to continue work.

#1073 Contributor Commission For ProjectManager

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTask.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTask.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoicedTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

PR for #1075 
Renamed original commission to projectCommission;
Added and tested attribute contributorCommission;

#1075 StoredInvoicedTask Takes Contributor Commission

---

self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java

PR for #1076 
Specify the contributor's commission as well, when registering a new PM;
Renamed old percentage to projectPercentage;

#1076 register PM with contributorCommission as well

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-api/src/main/java/com/selfxdsd/api/InvoicedTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/InvoiceTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/InvoiceTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoicedTasks.java

PR for #1077 
Added contributorCommission to Invoice.register(...);
Renamed old commission to projectCommission;
Added contributorCommission to InvoicedTasks.register(...);
Updated unit tests;

#1077 Invoice.register(...) Takes Contributor Commission

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

PR for #1079 
Implemented and tested contributorCommission();
Left puzzle to take this commission into account when making the payment;
Left puzzle to load the InvoicedTasks eagerly on the StoredInvoice;

#1079 StoredInvoice.contributorCommission()

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripePaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

#1090 different exception messages

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/RegisterUnsuccessfulPayments.java

#1094 failReason trimmed at 500 chars

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java

#1098 cache stripe Account in Supplier

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java

PR for #1101 
The Account supplier is initialized in the constructor;
Wrote unit tests;

#1101 StripePayoutMethod Account Supplier In Constructor

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/Country.java

#1104 treat UK as outside SEPA too

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/TaskIsRegistered.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Fixes #1103 
Check for the ``no-task`` label;
Use the Steps approach;
Updated unit tests;

#1103 reopenedIssue: check for 'no-task' and use Steps

---

self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java

#1114 Gitlab#follow implemented and tested.

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/TaskIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/TaskIssueTestCase.java

Fixes #938 
Implemented TaskIssue and added unit tests.
Left puzzles to continue work.

#938 Implementing TaskIssue

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Task.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/TaskIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/WithContributorLabel.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/TaskIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/WithContributorLabelTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryResignations.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

PR for #1124 
Implemented and tested Issue.etag() and Task.etag();

#1124 Issue.etag() and Task.etag() implemented

---

self-api/src/main/java/com/selfxdsd/api/storage/JsonStorage.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/main/java/com/selfxdsd/core/ConditionalJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java

#1137 JsonStorage exposed to Storage API.

---

self-core-impl/src/main/java/com/selfxdsd/core/Bitbucket.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java

#1138 Integrated ConditionalJsonResources with Self Providers.

---

self-core-impl/src/main/java/com/selfxdsd/core/Resource.java

#1144 fix EOF JsonException on empty body

---

self-core-impl/src/main/java/com/selfxdsd/core/ConditionalJsonResources.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java

#1134 Added overloaded methods for remaining HTTP methods.

---

checkstyle.xml
self-core-impl/src/main/java/com/selfxdsd/core/CreateRepoLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoLabels.java
self-core-impl/src/test/java/com/selfxdsd/core/CreateRepoLabelsTestCase.java

Fixes #1150 
Implemented and tested the CreateRepoLabels invitation;
Used it for Github and GiLab;

#1150 CreateRepoLabels added

---

self-api/src/main/java/com/selfxdsd/api/Repo.java
self-api/src/main/java/com/selfxdsd/api/Stars.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketStars.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubStars.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabStars.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketStarsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubStarsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabStarsTestCase.java

pr for #1153 
left puzzle for `GitlabStars#isStarred()` implementation.

#1153 Added method Repo#isStarred() via Stars#isStarred().

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabStars.java
self-core-impl/src/main/java/com/selfxdsd/core/ResourcePaging.java
self-core-impl/src/test/java/com/selfxdsd/core/ResourcePagingTestCase.java

pr for #1155
This will be used to implement `GitlabStars#added()`.

#1155 Resource paging to assist Github/Gitlab resources.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoInvitations.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoInvitationsTestCase.java

Fixes #1159 
Return gitlab invitations only if the repo is not starred.
Unit tests.

#1159 GitlabRepoInvitations only if repo is NOT starred

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabStars.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabStarsTestCase.java

#1157 GitlabStars#added() implemented and tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubPersonalRepos.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubPersonalReposTestCase.java

#1166 GithubPersonalRepos implemented and tested + todo for bug

---

self-core-impl/src/main/java/com/selfxdsd/core/ConditionalJsonResources.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubPersonalRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/ResourcePaging.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/ResourcePagingTestCase.java

#1169 ConditionalJsonResources supports Cache-Control: no-cache header.

---

self-api/src/main/java/com/selfxdsd/api/Repos.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabPersonalRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabPersonalReposTestCase.java

#1174 GitlabPersonalRepos implemented and tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabPersonalRepos.java

#1178 Fixed compilation error.

---

self-api/src/main/java/com/selfxdsd/api/storage/JsonStorage.java
self-core-impl/src/main/java/com/selfxdsd/core/ConditionalJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java

#1185 added JsonStorage.updateResource

---

self-api/src/main/java/com/selfxdsd/api/Resource.java
self-api/src/main/java/com/selfxdsd/api/storage/JsonStorage.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java

#1187 added String::Resource.body()

---

self-api/src/main/java/com/selfxdsd/api/Resource.java
self-api/src/main/java/com/selfxdsd/api/storage/JsonStorage.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java

#1190 removed Resource.newBuilder()

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java

#1193 follow redirects in JsonResources

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-api/src/main/java/com/selfxdsd/api/Projects.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java

#1996 started on Project renaming and left puzzles

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

#1200 unit tests for StoredProject.rename(...)

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#1204 REPO_RENAMED handled and tested

---

self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubWebhooksTestCase.java

#1198 added 'repository' event to GithubWebhooks

---

self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

#1208 remove Webhook change from StoredProject.rename(...)

---

self-api/src/main/java/com/selfxdsd/api/Projects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

Fixes #1210 
Left puzzle to continue with some unit tests.

#1210 Projects.getByWebHookToken implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java

PR for #1212 
Wrote unit tests and fixed bug (repoFullName was being compared instead of webHookToken).

#1212 unit tests and bugfix

---

self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java

Fixes #1215 
Start by catching any RuntimeException while reviewing project tasks (assigned and unassigned);
Left puzzle to continue;

#1215 Catch RuntimeException While Iterating Project Tasks

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/XmlBnr.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/XmlBnrTestCase.java

#1223 BNR default eurToRon to 492

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/GithubWebhookEvent.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/GitlabWebhookEvent.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GithubWebhookEventTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GitlabWebhookEventTestCase.java

#1228 Creating task estimation event type at WebHook level.

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java

#1233 Task/Tasks api supports update estimation.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#1234 PM handles issue estimation label changes.

---

self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

#1243 Remaining tests for *Tasks update estimation.

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/GithubWebhookEvent.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/GitlabWebhookEvent.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GithubWebhookEventTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/GitlabWebhookEventTestCase.java

#1262 handle only created comment from Github

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/IssueEstimationChanged.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/UpdateTaskEstimation.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#1265 started refactoring of estimation update to use Steps

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/UpdateTaskEstimation.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UpdateTaskEstimationTestCase.java

#1270 UpdateTaskEstimation implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/IssueEstimationChanged.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/IssueEstimationChangedTestCase.java

#1267 unit tests for IssueEstimationChanged

---

self-core-impl/src/main/java/com/selfxdsd/core/GlobalHttpClient.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java

#1278 global http client

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#1268 Check for closed issue before handling label changes.

---

self-core-impl/src/test/java/com/selfxdsd/core/managers/ConfusedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/DeregisterTestCase.java
self-core-impl/src/test/resources/responses_en.properties

#1281 updated messages

---

self-api/src/main/java/com/selfxdsd/api/PlatformInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/StoredPlatformInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/XmlBnrTestCase.java

#1291 new company address after 15th August 2022

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/XmlBnr.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/XmlBnrTestCase.java

#1294 more realistic BNR fallback exchange rate

---

self-api/src/main/java/com/selfxdsd/api/EmailNotification.java
self-api/src/main/java/com/selfxdsd/api/EmailNotifications.java
self-core-impl/src/main/java/com/selfxdsd/core/MailjetEmailNotifications.java
self-core-impl/src/main/java/com/selfxdsd/core/PlatformInvoiceEmailNotification.java

#1296 started email notifications

---

self-core-impl/src/main/java/com/selfxdsd/core/MailjetEmailNotifications.java
self-core-impl/src/main/java/com/selfxdsd/core/PlatformInvoiceEmailNotification.java
self-core-impl/src/test/java/com/selfxdsd/core/PlatformInvoiceEmailNotificationTestCase.java

#1298 unit tests for PlatformInvoiceEmailNotification
