pom.xml

#19 
added required dependency for coveralls plugin. JDK 11 kicked out the jaxb api.

#19 jaxb dependency for coveralls plugin

---

self-api/src/main/java/com/selfxdsd/api/Provider.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubSelfTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryUsers.java

PR for #20 
* Interface ``Repos`` replaced with ``Provider``. At the moment we are interested only in the public repositories which can be fetched and displayed on the front-end, while the backend expects only the repo's name to fetch it from the provider;
* ``Github`` is the first Provider we have;
* Left puzzle for continuing with method ``Github.repo()``;

#20 Repos replaced with Provider

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/storage/Storage.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContractsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java

PR for #79 
* Implemented ``Contributors`` and ``InMemoryContributors`` with methods ``register`` and ``getById``
* Used them inside ``InMemoryContracts``
* Updated unit tests for ``InMemoryContracts``
* Left puzzle for unit testing ``InMemoryContracts``
* Left puzzle for implementing ``Project :: Projects.getById``
* Left puzzle for implementing ``StoredContract``.

#79 InMemoryContributors.getById + register

---

self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

PR for #136 
Added `ofContributor(UserName,ProviderName)` in Tasks.
Stubbed `InMemoryTasks#ofContributor()`
Contributor#tasks() impl will return ContributorTasks via `storage.tasks.ofContributor`.
Implemented and tested `ContributorTasks`.
Implemented and tested `StoredContributor#tasks()`.
Removed puzzle.

#136 Implemented and unit tested Contributor.tasks()

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java

PR for #141 
Test case for `ofContributor` is incomplete for now.
Added puzzle to update the test case when api permits
assigning a task to a contributor.

#141 implemented InMemoryTasks#ofContributor.

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java

fixes #178 
* PM.provider() now returns the (authenticated) ``Provider``.
* PM.accessToken() removed since we don't need it anymore.

Added Provider :: PM.provider()

---

self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java

PR for #186 
Fixed bug in ProjectTasks#ofContributor & ContributorTasks#ofProject.
They return now the correct tasks relative to the provided List<Task>.
Updated tests to reflect that.

#186 - Fixed bug in ProjectTasks & ContributorTasks

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java

fixes #205 
If the Project and Contributor are not given as ctor parameters, they will be read from the Storage.

#205 SelfContract lazy-loading of Project and Contributor

---

self-api/src/main/java/com/selfxdsd/api/Invitation.java
self-api/src/main/java/com/selfxdsd/api/Invitations.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java

Fixes #190 
Implemented Invitations for Github.
Left puzzle to continue with ``GithubInvitation``.
Left puzzle to abstract the HTTP calls under an interface called ``JsonResources``.

#190 Started implementing Invitations for Github

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java

Fixes #192 
* Elect a Contributor for a given Task
- if the Task has an assignee, that contributor is not eligible for election
- out of the eligible contributors (the ones that have a Contract with the required role), one is elected randomly.
* Unit tests.

#192 Finished Contributors.elect(Task) + unit tests

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/main/java/com/selfxdsd/core/Resource.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

Fixes #226 
- Started interface JsonResources with implementing class JdkHttp
- Used it inside Github and Gitlab to abstract the GET Repo call
- Left puzzles to continue with JsonResources methods such as post, patch etc
- Left puzzle for writing integration tests for JsonResources, using Grizzly mock Http Server.

#226 started implementing JdkHttp JsonResources

---

self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/RandomPort.java

PR for #235 
* Used MkGrizzlyContainer (in-memory HTTP Server) to write integration tests for ``JdkHttp``
* For some reason, the JDK http calls to localhost are quite slow (1min/request). It's probably an Issue in the JDK.

#235 JdkHttp Integration Tests with MkGrizzlyContainer

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesITCase.java

fixes #239 
* Made GithubIssue/s work with JsonResources instead of making direct HTTP calls
* Mage classes GithubIssues and GithubIssue package protected in the core package -- they should not be visible to the outside.

#239 GithubIssue/s uses JsonResources + made classes package protected

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueCommentsITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java

PR for #248 
Implemented JsonResources :: JsonResources.authenticated(accessToken).
This way, JsonResources encapsulates the accessToken and doesn't expect it as method param, so
we will not have to pass around the token anymore.

#248 Authenticated JsonResources

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java

PR for #251 
GithubInvitations now uses JsonResources
Bug fix -> "Authorization" header instead of "Authentication".

#251 GithubInvitation uses JsonResources + fix Authorization header

---

self-api/src/main/java/com/selfxdsd/api/Comments.java
self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/Issues.java
self-api/src/main/java/com/selfxdsd/api/Project.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/DoNotRepeatTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueCommentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

Fixes #278 
Added the Event interface which represents an Event sent to Self via one of the webhooks.
Added Issues.received to create an Issue from a JsonObject (a webhook event usually has the Issue in json).
Added Comments.received to create a Comment from a JsonObject (a webhook event can contain a comment in json)
Added unit tests
Changed Project.resolve(JsonObject,...) to Project.resolve(Event,...);

Event interface, Issues.received, Comments.received

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

PR for #317 
An Invoice can now register a Task. It will also check if the Task belongs to the same Contract or if it is paid already (it will complain in both situatons). 
Added unit tests too.

#317 Invoice.register(Task) + unit tests

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java

- also fixed Gitlab integration tests to fetch repo by name instead of by id.
Fixes #337

#337 Fixed GitlabRepo Uri creation from name.

---

self-api/src/main/java/com/selfxdsd/api/Provider.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StoredProjectTestCase.java

Fixes #333 
The method now accepts the owner as well - it was not correct to assume that the owner was always the authenticated User, since the owner can also be an Organization.

#333 Provider.repo(name) -> Provider.repo(owner, name)

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

fixes #361 
* GithubRepo and GitlabRepo pass on the "activate" Event to the registered project
* Event is resolved and handled by the PM (using InvitePm and SetupWebhook steps)
* Created Event.Type class of constants
* Added unit tests for both GithubRepo.activate and GitlabRepo.activate
* Removed superficial integration test.

#361 resolve ACTIVATE event + unit tests

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java

PR for #380 
When electing a Contributor, we must also make sure that the final price of the Task goes into the available budget of the Project.
Added unit tests.
Left puzzle to implement Wallet.pay(...)

#380 Elect only affordable contributors

---

self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java

It moves comparesStoredContributorObjects and verifiesStoredContributorHashcode to the right place. #387

It moves comparesStoredContributorObjects and verifiesStoredContributorHashcode unit tests

---

self-api/src/main/java/com/selfxdsd/api/Task.java
self-api/src/main/java/com/selfxdsd/api/Tasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContractTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ContributorTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/ProjectTasksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/StoredTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/tasks/UnassignedTaskTestCase.java

- added the corespondent method in Tasks Api.
- implemented and tested unassign() for filter Tasks classes.
- left puzzle to test InMemoryTasks#unassign()
PR for #431

#431. Implemented+tested Task::unassign().

---

self-api/src/main/java/com/selfxdsd/api/Contributors.java
self-api/src/main/java/com/selfxdsd/api/storage/Paged.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributorsTestCase.java

- added creator method helper for Page.all representation.
- ProjectContributors is defaulted to `Page.all` as starting page to prevent faulty results in elect() pool.
- InMemoryContributors is now using a TreeMap for table in order to have a better control over its keys in testing.
- updated puzzle
PR for #371

#371. Paged Contributors implemented+tested.

---

self-api/src/main/java/com/selfxdsd/api/exceptions/RepoAlreadyActiveException.java
self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoTestCase.java

#479. Repo#activate() throws RepoAlreadyActiveException if active.

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/Confused.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Deregister.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Hello.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/SendReply.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Status.java

PR for #491 
Added a simple String ctor for SendReply, to clean up the composition where SendReply is being used. Most of the times, SendReply is the last step in any conversation, so a final step logging "Conversation ended" is enough.

#491 Simple ctor for SendReply, to ease its usage 

---

self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/InvitePm.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/InvitePmTestCase.java

Fixes #516 
The ``permission`` parameter is only applicable for orgs -- if it's a user repo, the request will fail with ``422 UNPROCESSABLE ENTITY``. Since the default permission level is ``push`` (which is good enough), we removed this parameter.

#516 Removed permission param when inviting Repo Collaborator

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Issues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java

Fixes #525  
Also added the option to specify labels for the newly opened Issue (Github will create the labels if they do not exist).
Left puzzle to implement ``Issue.close()``.

#525 Issues.open(title, body, labels) implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/PayoutMethod.java
self-core-impl/pom.xml
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java

PR for #541 
Instead of offering just an accessor method for the ``onboarding`` flag, we decided to offer an accessor method for the whole ``javax.json.JsonObject``, representing the whole PayoutMethod/Account, because we will need more information than just that flag and we want to avoid multiple useless API calls.

#541 PayoutMethod.json() implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueCommentsITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/resources/responses_en.properties

- added test for this use case.
- added test for deadline reminder.
- ~~re-added "slash" at the end of `commentsUri` in GithubIssueComments ctor. Without it, some
GithubIssueComments tests fail (Uri#resolve used in those tests will eat the 'comments' uri path segment)~~
PR for #564

#564. StoredProjectManager#assignedTasks handle missing task deadline

---

self-core-impl/src/main/java/com/selfxdsd/core/Env.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabWebhooks.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubWebhooksTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabWebhooksTestCase.java

Fixes #582 
The base uri for the Webhook can now be specified via the ``self_webhook_base_url`` env variable.

#582 added Env.self_webhook_base_url

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/IssueIsClosed.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/IssueIsClosedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RegisterTestCase.java
self-core-impl/src/test/resources/responses_en.properties

Fixes #587 
When registering an issue as a task, we should first check if the Issue is closed or not.
Added IssueIsClosed precondition Step and unit tests for it.

#587 When registering task, check for Issue closed

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/UnassignTask.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/DeregisterTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnassignTaskTestCase.java
self-core-impl/src/test/resources/responses_en.properties

PR for #603 
When unasigning a Task we should also remove the assignee from the Issue.
Better deregister comment.
Updated test.

#603 UnassinTask removes the Issue assignee as well

---

self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Issues.java
self-core-impl/src/main/java/com/selfxdsd/core/FoundIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/IssueHasLabel.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/FoundIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/IssueHasLabelTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Fixes #627 
Implemented and tested ``IssueHasLabel`` Step.
Moved method ``Labels :: labels()`` from interface ``Issues`` to interface ``Issue``.
Refactored StoredProjectManager.newIssue(...) to a Step-based approach.

#627 newIssue: check for the 'no-task' label

---

self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java

Fixes #629 
Github is passed down to GithubInvitation for starring the Repo after accepting Invitation.
Added logging and removed old puzzle.
Left puzzle to actually star the repo after we have method Repo.star() in place.

#629 Github passed to GithubInvitation for Repo starring

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/AssignTaskToIssueAssignee.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorHasRoles.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Deregister.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/IssueAssigneeHasRoles.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/IssueIsAssigned.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/UnassignIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/UserHasRoles.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AssignTaskToIssueAssigneeTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/AuthorHasRolesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/IssueIsAssignedTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/UnassignIssueTestCase.java
self-core-impl/src/test/resources/responses_en.properties

Fixes #626 
* Added and tested new steps: 
* IssueAssigneeHasRoles
* IssueIsAssigned
*  UnassignIssue
*  AssignTaskToIssueAssignee
* Modified the Step composition in StoredProjectManager.newIssue().
- if the new issue has an assignee who is a contributor with required role -> assign the task to them
- if the new issue has an assignee who is NOT a contributor with required role -> unassign issue
* Added new comments properties.

#626 Handle New Issues with assignee

---

self-api/src/main/java/com/selfxdsd/api/Commit.java
self-api/src/main/java/com/selfxdsd/api/Commits.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCommit.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCommitComments.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCommits.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitCommentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java

Fixes #646 
Implemented Github Commits - get and receive a Commit.
Implemented Github Commit Comments - post a comment in a commit or receive a commit comment
Wrote unit tests

#646 Github Repo Commits & Commit Comments Implemented

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java

PR for #651
We needed to change this logic because the JSON that comes from the Webhook pull_request event does not have the ``pull_request`` child object.

#651 changed GithubIssue.isPullRequest() logic

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Fixes #676 
If the PM is the author of a new or reopened ticket, it should not reply to itself.

#676 reply to new/reopened ticket only if author != self

---

self-api/src/main/java/com/selfxdsd/api/storage/Labels.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueLabels.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/WithContributorLabel.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueLabelsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/WithContributorLabelTestCase.java

Fixes #689 
* Added and tested WithContributorLabel issue decorator
* Contributor tag (e.g. ``@amihaiemil``) is now added/removed when the issue is assigned/unassigned
* Left puzzle for GithubRepoLabels.

#689 add or remove contributor label

---

self-api/src/main/java/com/selfxdsd/api/ProjectManager.java
self-api/src/main/java/com/selfxdsd/api/ProjectManagers.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProjectContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ProviderContributorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagersTestCase.java

Fixes #711 
* StoredProjectManager takes commission as ``double``
* Method ProjectManager.percentage() to return the double percentage
* Method BigDecimal::ProjectManager.commission(...) to calculate the effective commission for a value
* Updated dependent code
* Updated tests (and added test for the new ``commission(...)`` method).
* Updated ProjectManagers.register(...) to accept the commission as double percentage.

#711 Manager Commission as Percentage

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

#717 Started implementing GitlabIssues.

---

self-api/src/main/java/com/selfxdsd/api/Estimation.java
self-api/src/main/java/com/selfxdsd/api/Issue.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/LabelsEstimation.java
self-core-impl/src/main/java/com/selfxdsd/core/WithContributorLabel.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/LabelsEstimationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/WithContributorLabelTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/DeregisterTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/RemoveTaskTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasks.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java

Fixes #736 
- Issue.estimation() returns Estimation
- Estimation is read from Labels (e.g. ``45 min``)
- Default Estimation is 60min for Issues and 30min for PRs
- Min Estimation is 15min, Max estimation is 360min
- Wrote unit tests and adapted existing unit tests.

#736 Estimation read from Labels

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesTestCase.java

Fixes #738 
Before opening an Issue with some labels, we register these labels in the Repo first (in order to give them a color).

#738 register repo labels before opening Issue

---

self-api/src/main/java/com/selfxdsd/api/Invitation.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java
self-core-impl/src/main/java/com/selfxdsd/core/HelloIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/StarRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubInvitationTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/HelloIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/StarRepoTestCase.java

Fixes #740 
When opening the introductory issue, address it to the inviter.
Problem with ``this.repo.owner()`` was that the Github instance in use belongs to the PM, so ``owner()`` returns the PM.

#740 specify inviter tag on HelloIssue

---

self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoInvitations.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoInvitationsTestCase.java

PR for #303 
Implemented an empty GitlabRepoInvitations, because in the case of Gitlab there are no invitations to accept ever (when we invite the PM, they are automatically added as a Member).

#303 GitLab Invitations implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/StoredContractTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

Fixes #751 
Added and tested methods Contract.revenue() and Invoice.amount();
They both represent the Contributor's money from the Contract (tasks + active invoice) and from the Invoice, respectively.

#751 Contract.revenue and Invoice.amount implemented + tested

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Fixes #764 
Before, we were sending the whole amount to the Contributor and ask Stripe to give us back our commission (application fee). The problem with this approach is that the application fee comes back to us in the currency of the Contributor's account.
Now, we are sending the Contributor only his revenue (Invoice.amount), which means we are keeping on to our commission directly (``Invoice.totalAmount minus Invoice.amount``)

#764 less amount at destination

---

self-api/src/main/java/com/selfxdsd/api/Webhook.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabWebhooks.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubWebhooksTestCase.java

PR for #759 
* Implemented and tested GithubWebhooks.iterator() which we use to iterate over hooks and find the ones containing ``//self-xdsd.``;
* Implemented and tested GithubWebhooks.remove() (using iterator to get the ids to be deleted);
* Added puzzle for Project.deactivate(Repo).

#759 GithubWebhooks.remove() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Contract.java
self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ContributorContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/ProjectContracts.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProviderContributors.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/AuthorIsAssignee.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredResignation.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/StoredTask.java
self-core-impl/src/main/java/com/selfxdsd/core/tasks/UnassignedTasks.java

Fixes #793 
The problem was about equals comparison in Contract id, which should have been equalsIgnoreCase.
For safety reasons, we changed all the equals for username, repoFullName and provider to equalsIgnoreCase.

#793 equalsIgnoreCase repoFullName, provider, username everywhere

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Fixes #797 
Removed 
```java
this.storage.tasks().remove(task);
```
from StoredProjectManager.assignedTasks(...);
The task should be removed from the tasks table within the same DB transaction as InvoicedTasks.register.

#797 remove Task should happen inside InvoicedTasks.register

---

self-core-impl/src/main/java/com/selfxdsd/core/LabelsEstimation.java
self-core-impl/src/test/java/com/selfxdsd/core/LabelsEstimationTestCase.java

Fixes #794 
LabelEstimation regex modified to accept a number with max 6 digits.
Added unit tests.

#794 LabelEstimation ignored huge numbers + unit tests

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

Fixes #811 
Implemented Invoice billedBy and billedTo.
If the two values are not set in the constructor, then they are read from the Contract.
The two values are written in the DB (thus can never change) when the invoice is paid.

#811 Implemented Invoice.billedBy and billedTo

---

self-api/src/main/java/com/selfxdsd/api/Contributor.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java

Fixes #821 
We send the BillingInfo to Stripe Connect when creating a Connected Account.
The building logic is different on whether the Account is an Individual or a Company.

#821 send BillingInfo to Stripe Connect

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabComment.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueComments.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoInvitations.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommentTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoInvitationsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/IsComment.java

Per #726: 
- Basic implementation for `GitlabComment` & `GitlabIssueComments`

#726: Implement GitlabComment & GitlabIssueComments

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommitComment.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueComment.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueComments.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitCommentTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java

Fixes #838
We now have 2 type of comments for Gitlab API, one for issues and other for commits, because of the difference in JSON representation.

#838 GitlabCommitComment and GitlabIssueComment impl

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Fixes #850 
Before, we were calculating the commission with a 2-digit precision, which was wrong because BigDecimal is already the lowest denomination (cents), meaning it was possible to have commissions with a precision bellow cents, thus causing rounding errors.
Now we are calculating with a 0 scale and we are rounding half up, so we will always have an integer number of  cents.

#850 PM Commission calculated as 0-scale, rounded up BigDecimal (cents)

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java

PR for #855 
The contributorVat on the Invoice is a payment flag, together with paymentTime and transactionId.
It's being set after the Invoice is successfully paid.

#855 Implemented Invoice.contributorVat()

---

self-api/src/main/java/com/selfxdsd/api/Collaborator.java
self-api/src/main/java/com/selfxdsd/api/Collaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborator.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorTestCase.java

PR for #852 
- Add `Collaborator` interface and implement `GitlabCollaborator`
- Make `Collaborators` and `Iterable` of `Collaborator`

#852 Making Collaborators an iterable of Collaborator

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Fixes #889 
If status of the PaymentIntent is not ``succeeded`` or ``processing``, we cancel it.

#889 cancel PaymentIntent when status is not ok

---

self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/ContractInvoices.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/ContractInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

Fixes #891 
Added the EUR-RON exhange rate to Invoices.registerAsPaid(...);
Left puzzle to read this exchange rate from some API (in the case of real Stripe payment);

#891 registerAsPaid with EUR-RON exchange rate

---

self-api/src/main/java/com/selfxdsd/api/Bnr.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/XmlBnr.java

PR for #894 
Implemented Bnr and XmlBnr to fetch the EUR-RON exchagne rate from the Romanian National Bank;
Changed StripeWallet to send the BNR exchange rate when registering an Invoice as paid;

#894 XmlBnr implemented and used in StripeWallet

---

self-core-impl/src/main/java/com/selfxdsd/core/AccessToken.java
self-core-impl/src/test/java/com/selfxdsd/core/AccessTokenTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCollaboratorsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabWebhooksTestCase.java

Tokens generated with `self-web` will not work with `Private-Token` header (returns 401).
`AccesToken.Gitlab` has now the following config:
- header: `Authorization`
- value: `Bearer <token>`
--
Tested with a token generated with 'self-web' and now works fine.
No bounty needed, this is part of https://github.com/self-xdsd/self-web/issues/335

AccesToken.Gitlab updated to use "Authorization" header.

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommit.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommits.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitCommentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommitsTestCase.java

Fixes #912 
Passes Collaborators down GitlabCommits and GitlabCommit;
GitlabCommit.author() iterates over Collaborators to find the username of the author;
Updated tests;

#912 Read GitlabCommit author from Collaborators

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationReposTestCase.java

- this key is needed to create GitlabRepo uri: json["_links"]["self"]
--
no bounty needed

Fixed bug where "_links" is not present in Gitlab org repos json.

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/PmProjects.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/UserProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PmProjectsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/UserProjectsTestCase.java

Fixes #917 
* Both UserProjects and PmProjects now encapsulate the Storage
* UserProjects.getProjectById() searches in the storage directly
* updated unit tests

#917 UserProjects.getProjectById() searches in Storage directly

---

self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabOrganizationReposTestCase.java

Passing `owned = true` as parameter won't stop to display repos to all org members.
Replacing it with `min_access_level = 40` (Maintainer or Owner) fixes it.
https://docs.gitlab.com/ee/api/members.html#valid-access-levels
--
no bounty

Fixed organization repo owner filter.

---

self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StoredContributorTestCase.java

Fixes #922 
The method now reads the Contract from Storage directly instead of iterating over all the Contracts of the Contributor.

#922 StoredContributor.contract(...) reads from Storage + unit tests

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubCommit.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubCommitTestCase.java

Fixes #952 
Covered the case when the commit author is missing in Github. Will return an empty username.

#952 GithubCommit.author() can be missing

---

self-api/src/main/java/com/selfxdsd/api/PayoutMethod.java
self-api/src/main/java/com/selfxdsd/api/PayoutMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/ContributorPayoutMethods.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/ContributorPayoutMethodsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/contributors/StripePayoutMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryPayoutMethods.java

PR for #988 
StripePayoutMethod.remove() implemented and tested;
StripePayoutMethod takes Storage as ctor argument;
ContributorPayoutMethods.remove(PayoutMethod) uses PayoutMethod.remove();

#988 PayoutMethod.remove() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Invoice.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/XmlBnr.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

Fixes #998 
Added Invoice.billedByCountry,billedToCountry and eurToRon;
If they are not set, they will be read from the Contract and BNR respectively;
Added tests;
Updated StripeWallet.pay(...) to set these values when registering the Invoice as paid.

#998 Invoice.billedByCountry,billedToCountry,eurToRon + tests

---

self-api/src/main/java/com/selfxdsd/api/PaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredPaymentMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/WalletPaymentMethods.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/WalletPaymentMethodsTestCase.java

PR for #1006 
StoredPaymentMethod.activate() doesn't filter for Wallet anymore;
WalletPaymentMethods.activate(PaymentMethod) calls PaymentMethod.activate();
Updated tests.

#1006 Fixed activation of PaymentMethod

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-api/src/main/java/com/selfxdsd/api/Wallets.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/ProjectWallets.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/ProjectWalletsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

Fixes #1004 
Implemented and tested Wallets.remove(Wallet);
Implemented and tested Wallet.remove();
Added puzzle for StripeWallet.remove() (needs to also remove the Customer from Stripe);

#1004 Wallets.remove(Wallet) implemented and tested

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java

Fixes #1019
Method StoredProjectManager.unassignedTasks(...) was searching for the Contributor. Instead, it should search for the Contract of the Contributor. Also updated tests.

#1019 StoredProjectManager.unassignedTasks searches for Contract

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

Fixes #1030 
Implemented FakeWallet.activate() which activates self or returns self if already active;
Implemented StripeWallet.activate() which activates self (and removes the Project's FakeWallet if present) or returns self if already active;
Added unit tests;

#1030 Wallet.activate() implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Invoices.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/ContractInvoices.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/ContractInvoicesTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java

Changes Invoice.registerAsPaid(...) to return the (successful) Payment.
We will register the succesful Payment through this method because it has to be done in the same transaction together with the update of the Invoice and creation of the PlatformInvoice (in the storage).
Updated tests.
Left puzzle to continue with Wallet.pay(...);

#1026 Invoices.registerAsPaid(...) returns Payment

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripePaymentMethodTestCase.java

Wallet.pay(...) now returns the registered (successful) Payment. 
Exceptions from the payment process are going to be caught in a decorator and registered as failed Payment. 
We will also write a decorator to pull out all the payment pre-checks.

#1034 Wallet.pay(...) returns the registered Payment

---

self-api/src/main/java/com/selfxdsd/api/Payment.java
self-api/src/main/java/com/selfxdsd/api/Payments.java
self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/RegisterUnsuccessfulPayments.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/RegisterUnsuccessfulPaymentsTestCase.java

PR for #1038
Implemented and tested the Wallet decorator RegisterUnsuccessfulPayments which catches exceptions thrown by the original Wallet.pay(...) and registers appropriate payments. 
Added unit tests for RegisterUnsuccessfulPayments.
Added Payment status ``ERROR``.
Left puzzle to implement ``InvoicePayments``.

#1038 RegisterUnsuccessfulPayments implemented and tested

---

self-api/src/main/java/com/selfxdsd/api/Wallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/PreCheckPayments.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/FakeWalletTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PreCheckPaymentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletTestCase.java

This decorator checks:
- if invoice is not part of the project associated with original wallet.
- if invoice is already paid.
- if invoice is at least 108EUR.
- if there is enough cash to pay the invoice.
Cleaned-up Stripe and FakeWallet and their unit tests.
pr for #1037

#1037 PreCheckPayments Wallet decorator impl+tested.

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketCommit.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketCommits.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketCommitsTestCase.java

The URIs for `BitbucketCommit` from `BitbucketCommits#getCommit()` and `BitbucketCommits#latest()` were wrong.
They were created by adding the ref to the base of commits URI.
`/<owner>/<name>/commits` -> `/<owner>/<name>/commits/hash`
But the correct form is `/<owner>/<name>/commit/hash` (commit not commits)
Interesting that when calling `getCommit()`, Bitbucket won't complain about it, and the result was just a json commits with a single commit.
Based on this, the extracted `BitbucketCommit` json from that result was wrong too. (it shouldn't contain the "values" property).

BitbucketCommit from BitbucketCommits URI fix.

---

self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganizationRepos.java
self-core-impl/src/test/java/com/selfxdsd/core/BitbucketOrganizationReposTestCase.java

PR for #984 
This impl assumes that  `BitbucketOrganizationRepos` has the correct repos URI which is not based on the following code:  
https://github.com/self-xdsd/self-core/blob/36dbcb49c816783d5c692f5ef004812a70240ccf/self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganization.java#L66-L73
because links in the json response have `!` prefix as in 
```
"repositories": {
"href": "https://bitbucket.org/!api/2.0/repositories/alilosoft"
}
``` 
and as discussed earlier with @criske those cause an authentication problem.
I will file an issue about it + other issues I found when working on this task :)

#984 BitbucketOrganizationRepos impl & test

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredPayment.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredPaymentTestCase.java

Fixes #1056 
StoredPayment takes only invoiceId; 
Updated method StoredPayment.invoice() and the unit tests;
Fixed equals and hashcode for StoredPayment;

#1056 StoredPayment Takes invoiceId

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/PreCheckPayments.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/RegisterUnsuccessfulPayments.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PreCheckPaymentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/RegisterUnsuccessfulPaymentsTestCase.java

Otherwise WalletPaymentMethods methods will equality check the  Wallet decorator
instead of it's delegate.

Decorator Wallets use equals/hashCode of original.

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/FakeWallet.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/PreCheckPaymentsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/RegisterUnsuccessfulPaymentsTestCase.java

Previous implementations were based on Wallet class comparing and attached project.
But when used with Wallet decorators, the "original" equal implementation
would not ensure commutativity.
Comparing based on Wallet#type instead of Wallet::class fixes the commutativity problem.
```java
Wallet original = StripeWallet(...)
Wallet decorator = PreChekPayments(original)
decorator.equals(original) //TRUE
original.equals(decorator) //FALSE
```

Wallet impls equals are now based on project and type.

---

self-api/src/main/java/com/selfxdsd/api/Event.java
self-api/src/main/java/com/selfxdsd/api/Language.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/Commands.java
self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java
self-core-impl/src/test/java/com/selfxdsd/core/managers/CommandsTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/LanguageLinkedResponsesTestCase.java
self-core-impl/src/test/resources/commands_en.properties
self-core-impl/src/test/resources/replies/commands.comment_en.md
self-core-impl/src/test/resources/responses_bad_link_en.properties
self-core-impl/src/test/resources/responses_en.properties

This PR also introduces linked language responses. This means that a value for a response key could be a link
to a separate file that contains the actual reply. The file, depending on used link protocol, could be fetched locally (`file://`, `classpath:`) or remotely (`http(s)://`).
By doing this, larger and/or marked up replies can be easly maintainted in separate files rather than having them clobbered in the `responses.properites`.
PR for #1071

#1071 `Commands` implemented + Language linked responses.

---

self-core-impl/src/main/java/com/selfxdsd/core/StoredPlatformInvoice.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

PR for #1084 
Contributor commission is deducted from the Contributor's gross earnings;
Contributor commission is taken into account when calculating the VAT;
Added the reverse charge (negate the VAT) for EU contributors which are paying VAT;
If reverse charge applies, VAT is NOT deducted from the Contributor's earnings;
Left puzzle to update the PlatformInvoice's PDF.

#1084 account for contributor commission when paying

---

self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/StoredInvoice.java
self-core-impl/src/test/java/com/selfxdsd/core/contracts/invoices/StoredInvoiceTestCase.java

PR for #1083 
Easier solution: StoredInvoice has a Supplier of InvoicedTasks which reads them from the Storage only once and caches the result;
Added unit test;

#1083 StoredInvoice caches its InvoicedTasks

---

self-core-impl/src/main/java/com/selfxdsd/core/projects/Country.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java

Fixes #1092 
If the Connected Account is from a non-SEPA country, use ``on_behealf_of``.

#1092 on_behalf_of for non-SEPA accounts

---

self-api/src/main/java/com/selfxdsd/api/PayoutMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/contributors/StripePayoutMethod.java
self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java
self-core-impl/src/test/java/com/selfxdsd/core/projects/StripeWalletITCase.java

Fixes #1097 
Implemented PayoutMethod.canReceivePayments();
Used it inside StripeWallet.pay();
Left puzzle for unit testing of StripePayoutMethod;

#1097 PayoutMethod.canReceivePayments()

---

self-api/src/main/java/com/selfxdsd/api/Provider.java
self-core-impl/src/main/java/com/selfxdsd/core/Bitbucket.java
self-core-impl/src/main/java/com/selfxdsd/core/FollowProjectOwner.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepoInvitations.java
self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoInvitations.java
self-core-impl/src/test/java/com/selfxdsd/core/FollowProjectOwnerTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubTestCase.java

PR for #1109 
Implemented and tested Provider.follow(username);
Implemented and tested FollowProjectOwner;
Implemented following of the PO when accepting the invitation;
Left puzzles to continue with GitLab.

#1109 Follow the Github project Owner

---

self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepoInvitations.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabRepoInvitationsTestCase.java

PR for #1113 
When 'accepting' Gitlab invitations, we star the repo and follow the PO.
There are no actual Gitlab invitations ever, so we return a mock invitation (based on the Project) for each project.

#1113 star repo, follow PO when 'accepting' Gitlab invitations

---

self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabITCase.java

Fixed bug in Gitlab#findUserId(username) where result is an array of at most one element and not an object.
When user is not found, array is empty.
FIXES #1119

#1119. Fixed bug in Gitlab#findUserId.

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubIssues.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssueTestCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubIssuesITCase.java
self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueTestCase.java

PR for #1123 
We don't read the JSON issue directly when calling GithubIssues.getById(); instead, the JSON is read and cached into an encapsulated Supplier (inside GithubIssue) only when needed the first time.
Updated unit tests.

#1123 GithubIssue works with Supplier of Json

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/mock/MockJsonResources.java

Fixes #1128 
Overloaded GET and POST to also accept HTTP Headers;
Left puzzle for the rest of the methods.

#1128 JsonResources allow specification of headers

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/JdkHttpITCase.java

Problem was that the version of Grizzly/MkGrizzlyContainer used in test doesn't support HTTP_2, the default protocol for jdk HTTPClient.
The fix was to add a flag to instruct the client to use HTTP_1_1.
This is why the client in each test hanged for about a minutes until gave up and throw EOFException.
Here is the debug log:
```java
DEBUG: [HttpClient-1-SelectorManager] [60s 747ms] SocketTube(1) got read EOF
DEBUG: [HttpClient-1-SelectorManager] [60s 747ms] SocketTube(1) pausing read event
DEBUG: [HttpClient-1-SelectorManager] [60s 748ms] SelectorAttachment Registering jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent@6897fcd7 for 0 (false)
DEBUG: [HttpClient-1-SelectorManager] [60s 748ms] SocketTube(1) completing subscriber
DEBUG: [HttpClient-1-SelectorManager] [60s 748ms] …
```

Fixed slow integration tests.

---

self-core-impl/src/main/java/com/selfxdsd/core/ConditionalJsonResources.java
self-core-impl/src/test/java/com/selfxdsd/core/ConditionalJsonResourcesTestCase.java

This happens for gitlab header, where "ETag" is as "etag".
Because of this,  saving the Resource body into JsonStorage was skipped.

Fixed bug where etag header with different casing is ignored.

---

self-core-impl/src/main/java/com/selfxdsd/core/BaseRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/BitbucketRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/Github.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java

PR for #1167 
Sometimes we already have the Repo json (e.g. organization repos), so we save it in BaseRepo to avoid a useless api call.

#1167 Repo with existing Json

---

self-api/src/main/java/com/selfxdsd/api/Repos.java
self-core-impl/src/main/java/com/selfxdsd/core/GithubPersonalRepos.java
self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java
self-core-impl/src/main/java/com/selfxdsd/core/ResourcePaging.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubTestCase.java

PR for #1171 
Split JDK HttpHeaders by comma manually;

#1171 split headers by comma manually

---

self-core-impl/src/main/java/com/selfxdsd/core/JsonResources.java

Fixes #1229
Also using Connection Timeout of 10s.

#1229 use and close our own ExecutorService for HTTP Requests

---

self-core-impl/src/main/java/com/selfxdsd/core/GithubRepo.java
self-core-impl/src/test/java/com/selfxdsd/core/GithubRepoTestCase.java

PR for #1252 
Used ``MockJsonResources`` instead of MkGrizzly, as other tests.

#1252 unit tests for GithubRepo.enableIssues()

---

self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java

This logic will be tested along with #1271.
Pr for #1269

#1269 Send a comment after updating task estimation.
